import { OnInit, ElementRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare class NgxNumberFormatDirective implements ControlValueAccessor, OnInit {
    private el;
    private _oldValueForDetectChange;
    private _oldValue;
    private _displayValue;
    private _max;
    private _decimal;
    private _format;
    private _formElement;
    private _specialKeys;
    private _regExNumber;
    private _regExNumberAndDecimal;
    private _oldSelectionStart;
    private _detectDelete;
    private _detectBackspace;
    private _detectSelectAll;
    private _process;
    onChange: (_: any) => void;
    onTouch: () => void;
    constructor(el: ElementRef);
    ngOnInit(): void;
    initialize: string;
    onKeyDown(event: KeyboardEvent): void;
    onClick(event: any): void;
    onInput(event: any): void;
    onBlur(event: any): void;
    processCursorPosition(_oldValue: string, _oldSelectionStart: number, _newValue: string): void;
    setCursorAt(position: number): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState?(value: boolean): void;
    private onValueChange;
    private removeLeadingZero;
    private getRegEx;
    private setFormat;
}
